# Generated by Django 4.2.15 on 2024-12-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='country',
        ),
    ]
