# Generated by Django 4.2.15 on 2024-12-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_addressbook_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='label',
            field=models.CharField(choices=[('HM', 'HOME'), ('OFF', 'OFFICE')], default='Home', max_length=15, unique=True),
        ),
    ]
