# Generated by Django 4.2.17 on 2025-01-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_addressbook_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressbook',
            name='is_billing',
        ),
        migrations.RemoveField(
            model_name='addressbook',
            name='is_shipping',
        ),
        migrations.RemoveField(
            model_name='addressbook',
            name='phone',
        ),
        migrations.AddField(
            model_name='addressbook',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='building',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressbook',
            name='province',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='label',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default='Home', max_length=10),
        ),
    ]
