# Generated by Django 4.2.17 on 2025-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_addressbook_is_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='is_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addressbook',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
