# Generated by Django 4.2.17 on 2025-02-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_payment_paymentmethod_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
