# Generated by Django 4.2.15 on 2024-09-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='attributes',
            new_name='attribute_values',
        ),
    ]
