# Generated by Django 4.2.14 on 2024-08-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_variants_sku_alter_variants_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalues',
            name='thumnail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
