# Generated by Django 4.2.15 on 2024-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_attributes_variants_attribute_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
