# Generated by Django 4.2.14 on 2024-08-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attributevalues_thumnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='attribute_values',
        ),
    ]
