# Generated by Django 4.2.15 on 2024-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productreview_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.FloatField(default=2.5),
            preserve_default=False,
        ),
    ]
