# Generated by Django 4.2.15 on 2024-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productreview_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out of Stock')], max_length=20),
        ),
    ]
